### ISSUE TITLE
在配置kubelet 的步骤中，token 跟 集群内的 node 对应关系。

### ISSUE THREAD

**Issue by MrYueQ** [bmwx4/k8s-install#2]
老师，您好。 在配置kubelet 的步骤中，是每个实例节点都对应一个不同的token 还是 一个token 对应集群内的所有Node. 这两者有什么区别吗？
1. export BOOTSTRAP_TOKEN=$(kubeadm token create \
      --description kubelet-bootstrap-token \
      --groups system:bootstrappers:${node_name} \
      --kubeconfig ~/.kube/config)

**Comment by guanyuding** [comment]
一个实例或者node一个token
